"""campaigns

Revision ID: 52c30cea107e
Revises: 1699e2d713bc
Create Date: 2026-06-25 11:06:11.783046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '52c30cea107e'
down_revision: Union[str, Sequence[str], None] = '1699e2d713bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_name'), 'campaigns', ['name'], unique=True)
    op.add_column('records', sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.execute("UPDATE records SET subject='' WHERE subject IS NULL")
    op.alter_column('records', 'subject', nullable=False)
    op.add_column('records', sa.Column('campaign_id', sa.Integer(), nullable=True))
    op.execute("UPDATE records SET token='' WHERE token IS NULL")
    op.alter_column('records', 'token',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_foreign_key(None, 'records', 'campaigns', ['campaign_id'], ['id'])
    op.add_column('unsubscribed', sa.Column('id', sa.Integer(), sa.Identity(), nullable=False))
    # op.execute("UPDATE unsubscribed SET id=count(*) ")
    op.alter_column('unsubscribed', 'id', nullable=False)
    op.add_column('unsubscribed', sa.Column('campaign_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'unsubscribed', 'campaigns', ['campaign_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'unsubscribed', type_='foreignkey')
    op.drop_column('unsubscribed', 'campaign_id')
    op.drop_column('unsubscribed', 'id')
    op.drop_constraint(None, 'records', type_='foreignkey')
    op.alter_column('records', 'token',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('records', 'campaign_id')
    op.drop_column('records', 'subject')
    op.drop_index(op.f('ix_campaigns_name'), table_name='campaigns')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
