"""campaigns and db model changes

Revision ID: 932534ef1979
Revises: da158e986ff4
Create Date: 2026-05-18 16:05:49.037971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '932534ef1979'
down_revision: Union[str, Sequence[str], None] = 'da158e986ff4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('records', sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=""))
    op.add_column('records', sa.Column('campaign_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tracking', 'records', ['mid'], ['mid'])
    op.add_column('unsubscribed', sa.Column('campaign_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'unsubscribed', 'campaigns', ['campaign_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'unsubscribed', type_='foreignkey')
    op.drop_column('unsubscribed', 'campaign_id')
    op.drop_constraint(None, 'tracking', type_='foreignkey')
    op.drop_column('records', 'campaign_id')
    op.drop_column('records', 'subject')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
