"""init

Revision ID: c165121eba4b
Revises:
Create Date: 2026-03-13 11:31:45.901279

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "c165121eba4b"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "records",
        sa.Column("mid", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("from_", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("to", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("sent_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("mid"),
    )
    op.create_table(
        "tracking",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("mid", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("opened_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tracking_mid"), "tracking", ["mid"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tracking_mid"), table_name="tracking")
    op.drop_table("tracking")
    op.drop_table("records")
    # ### end Alembic commands ###
