services:
  ms:
    container_name: mailsender
    build: .
    volumes:
      - ./config:/config
      - ./credentials.json:/app/credentials.json
    ports:
      - 8990:8000
    environment:
      CONFIG_DIR: /config
      GMAIL__CREDENTIALS_FILE: /app/credentials.json
      DB__RECORDS_DB: postgresql://
      TRACKINGURL: localhost:8990
    restart: unless-stopped
    networks:
      # - giftcards
      - mailsender

  records:
    container_name: records_db
    image: postgres:15.17-trixie
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mails
    restart: unless-stopped
    networks:
      - mailsender

networks:
  # giftcards:
  #   external: true
  mailsender:
