services:
  ms:
    container_name: mailsender
    build: .
    volumes:
      - ./credentials.json:/app/credentials.json
      - ./token.json:/app/token.json
    ports:
      - 8990:8000
    restart: unless-stopped
    networks:
      - giftcards
      - mailsender

  records:
    container_name: records_db
    image: postgres:15.17-trixie
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mails
    restart: unless-stopped
    networks:
      - mailsender

networks:
  giftcards:
    external: true
  mailsender:
