from typing import Protocol
from sqlmodel import Session

# from sqlalchemy.base import Engine

class DBProtocol(Protocol):
    def create_engine(self): ...
    def get_session(self) -> Session: ...
    def create_db_and_tables(self) -> None: ...
